services:
  portainer_agent:
    container_name: protainer_agent
    image: portainer/agent:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer_server:
    container_name: portainer_server
    image: portainer/portainer-ee:latest
    command: -H tcp://portainer_agent:9001 --tlsskipverify
    restart: always
    ports:
      - 9443:9000
    volumes:
      - data:/data

volumes:
  data: