services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data:
    driver_opts:
      type: nfs
      o: "nfsvers=4,addr=127.0.0.1,rw"
      device: ":/rust/nfs/container-vols/portainer_config"